#pragma once

enum TEXTYPE	{ TEX_SINGLE, TEX_MULTI, TEX_END };

enum  OBJID     { OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_SHIELD, OBJ_UI, OBJ_END };

enum TILETYPE    { OPT_GROUND, OPT_WALL, OPT_ORE, OPT_DECO, OPT_END};
enum TILETERRAIN { TRN_DIRT, TRN_SAND, TRN_NATURE, TRN_STONE, TRN_WATER, TRN_END };
